version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    container_name: social-stream
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      #- /home/lpazc/Documentos/backup/dump/:/data/db
      # - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - mongodb_data_container:/data/db
    # command: mongorestore --drop --db berry /data/db/test/
volumes:
  mongodb_data_container: